language: node_js
node_js:
  - v5
  - v4
  - '0.12'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-nofx-webapp' ]; then cd .. && eval "mv $currentfolder generator-nofx-webapp" && cd generator-nofx-webapp; fi
before_script:
  - gem install sass
  - cd test/fixtures
  - npm install
  - cd ../..
